### ISSUE TITLE
luapath: env MACOSX_DEPLOYMENT_TARGET=10.5 gcc: command not found

### ISSUE THREAD

**Issue by daurnimator** [wahern/luapath#2]
Some of the fixes in https://github.com/wahern/luapath/commit/7843527e1db0d023d5ce16ee60c8fd868acfe2b0 were incorrect.
See https://github.com/wahern/cqueues/issues/46#issuecomment-171540624

**Comment by wahern** [comment]
Fixed in e055b224adcaceb2fee2d0d2e7b8ca7b9aa342bb.
